-- create tables
drop trigger dbopb_before_alter_trg;
drop table dbops_schemas;
drop table dbops_locks;

create table dbops_locks (
    id             number generated by default on null as identity
                   constraint dbops_locks_id_pk primary key,
    owner          varchar2(128 char) not null,
    object_type    varchar2(23 char) not null,
    object_name    varchar2(128 char) not null,
    locked_on      timestamp,
    locked_by      varchar2(255 char),
    notes          clob,
    created        timestamp not null,
    created_by     varchar2(255 char) not null,
    updated        timestamp not null,
    updated_by     varchar2(255 char) not null
);



create table dbops_schemas (
    id              number generated by default on null as identity
                    constraint dbops_schemas_id_pk primary key,
    owner           varchar2(128 char) not null,
    enabled_flag    varchar2(1 char) default on null 'N' constraint dbops_schemas_enabled_flag_ck
                    check (enabled_flag in ('Y','N')),
    created         timestamp not null,
    created_by      varchar2(255 char) not null,
    updated         timestamp not null,
    updated_by      varchar2(255 char) not null
);



-- triggers
create or replace trigger dbops_locks_biu
    before insert or update
    on dbops_locks
    for each row
begin
    if inserting then
        :new.created := localtimestamp;
        :new.created_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.updated := localtimestamp;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end dbops_locks_biu;
/


create or replace trigger dbops_schemas_biu
    before insert or update
    on dbops_schemas
    for each row
begin
    if inserting then
        :new.created := localtimestamp;
        :new.created_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.updated := localtimestamp;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end dbops_schemas_biu;
/


-- Generated by Quick SQL 1.2.9 28/09/2024, 20:54:20

/*
locks
    owner vc128 /nn
    object_type vc23 /nn
    object_name vc128 /nn
    locked_date date
    locked_by vc255

schemas
    owner vc128 /nn
    enabled_flag vc1 /check Y,N /default N

 Non-default options:
# settings = {"apex":"Y","auditcols":"Y","db":"23","prefix":"dbops","pk":"IDENTITY"}

*/

-- PLSQL packages
@dbops_lock_pkg.pls
@dbops_lock_pkg.plb

-- Triggers
@dbopb_before_alter_trg.sql

-- Grants
grant execute on dbops_lock_pkg to public;
create or replace public synonym dbops_lock_pkg for dbops.dbops_lock_pkg;