---
# ====== Application: DBOPS ==================================
id: 100
identification: 
  name: DBOPS
  alias: DBOPS
  version: Release 1.0

row-search: 
  tokenize: true
  text-query-function: None

availability: 
  status: Available with Developer Toolbar
  build-status: Run and Build Application

error-handling: 
  default-display-location: Inline with Field and in Notification

report-printing: 
  type: Native Printing

advanced: 
  friendly-urls: true
  allow-feedback: true
  logging: true
  debugging: true
  compatibility-mode: 21.2 to 24.1
  accessible-read-only-items: false
  pass-ecid: N

authentication: 
  public-user: APEX_PUBLIC_USER
  authentication-scheme: Oracle APEX Accounts # 14117896671377561

authorization: 
  authorization-scheme: Reader Rights # 15116136912581610
  run-on-public-pages: false
  run-on-background-job: true
  source-for-role-or-group-schemes: Access Control User Role Assignments

session-management: 
  rejoin-sessions: Disabled

session-state-protection: 
  enabled: true

security: 
  deep-linking: Disabled
  browser-cache: Disabled
  embed-in-frames: Deny
  referrer-policy: strict-origin
  html-escaping-mode: Extended
  runtime-api-usage: 
  - Modify This Application

database-session: 
  parsing-schema: DBOPS

globalization: 
  primary-language: English (en)
  document-direction: Left-To-Right
  language-derived-from: Application Primary Language
  automatic-time-zone: false
  automatic-csv-encoding: true

application-format-masks: 
  date: DS
  timestamp: DS
  timestamp-time-zone: DS

character-value-comparison: 
  behavior: Database session NLS setting (default)

logo: 
  type: Text
  text: '&APP_NAME.'

progressive-web-app: 
  enable: true
  installable: false
  display: Standalone
  screen-orientation: Any
  ios-status-bar-style: Default
  enable-push-notifications: false

navigation: 
  home-url: 
    url: 'f?p=&APP_ID.:1:&APP_SESSION.::&DEBUG.:::'
    page: 1 # Locks

  login-url: 
    url: 'f?p=&APP_ID.:LOGIN:&APP_SESSION.::&DEBUG.:::'
    page: LOGIN

navigation-menu: 
  list-template: Top Navigation Menu
  template-options: 
  - '#DEFAULT#'
  - js-tabLike
  list-position: Top
  list: Navigation Menu # 14118646852377564

navigation-bar: 
  implementation: List
  list: Navigation Bar # 14319027927377612
  list-template: Navigation Bar
  template-options: 
  - '#DEFAULT#'

javascript: 
  include-jquery-migrate: false

attributes: 
  theme: Universal Theme # 42
  global-page: 0
  enable-end-users-to-choose-theme-style: false
  add-"built-with-apex"-to-footer: false
  auto-dismiss-success-messages: false

substitutions: 
- # ====== Substitution: APP_NAME ==============================
  id: 1
  identification: 
    name: APP_NAME

  value: 
    static-value: DBOPS - Database Operation Tool

component-settings: 
- # ====== Component Setting: NATIVE_OPEN_AI_ASSISTANT =========
  id: 8552800107246988
  identification: 
    name: NATIVE_OPEN_AI_ASSISTANT
    type: Dynamic Action

  subscription: 
    version-number: 5501678

- # ====== Component Setting: NATIVE_ADFBC =====================
  id: 8553299590246988
  identification: 
    name: NATIVE_ADFBC
    type: REST Data Source

  subscription: 
    version-number: 5501678

- # ====== Component Setting: NATIVE_GEOCODING =================
  id: 8553346725246988
  identification: 
    name: NATIVE_GEOCODING
    type: Process

  settings: 
    attribute-1: RELAX_HOUSE_NUMBER

  subscription: 
    version-number: 5501678

- # ====== Component Setting: NATIVE_SELECT_MANY ===============
  id: 8553695240246988
  identification: 
    name: NATIVE_SELECT_MANY
    type: Item

  settings: 
    attribute-1: separated

  subscription: 
    version-number: 5501678

- # ====== Component Setting: NATIVE_DISPLAY_SELECTOR ==========
  id: 14114634859377559
  identification: 
    name: NATIVE_DISPLAY_SELECTOR
    type: Region

  subscription: 
    version-number: 5501678

- # ====== Component Setting: NATIVE_DATE_PICKER_APEX ==========
  id: 14114932329377560
  identification: 
    name: NATIVE_DATE_PICKER_APEX
    type: Item

  settings: 
    attribute-1: 'MONTH-PICKER:YEAR-PICKER'
    attribute-2: VISIBLE
    attribute-3: 15
    attribute-4: FOCUS

  subscription: 
    version-number: 5501678

- # ====== Component Setting: NATIVE_GEOCODED_ADDRESS ==========
  id: 14115182921377560
  identification: 
    name: NATIVE_GEOCODED_ADDRESS
    type: Item

  settings: 
    attribute-1: RELAX_HOUSE_NUMBER
    attribute-2: N
    attribute-3: 'POPUP:ITEM'
    attribute-4: default
    attribute-6: LIST

  subscription: 
    version-number: 5501678

- # ====== Component Setting: NATIVE_MAP_REGION ================
  id: 14115508222377560
  identification: 
    name: NATIVE_MAP_REGION
    type: Region

  subscription: 
    version-number: 5501678

- # ====== Component Setting: NATIVE_SINGLE_CHECKBOX ===========
  id: 14116084706377560
  identification: 
    name: NATIVE_SINGLE_CHECKBOX
    type: Item

  settings: 
    attribute-1: Y
    attribute-2: N

  subscription: 
    version-number: 5501678

- # ====== Component Setting: NATIVE_IR ========================
  id: 14116439605377560
  identification: 
    name: NATIVE_IR
    type: Region

  subscription: 
    version-number: 5501678

- # ====== Component Setting: NATIVE_COLOR_PICKER ==============
  id: 14116705750377560
  identification: 
    name: NATIVE_COLOR_PICKER
    type: Item

  settings: 
    attribute-1: FULL
    attribute-2: POPUP

  subscription: 
    version-number: 5501678

- # ====== Component Setting: NATIVE_STAR_RATING ===============
  id: 14117038658377560
  identification: 
    name: NATIVE_STAR_RATING
    type: Item

  settings: 
    attribute-1: fa-star
    attribute-4: '#VALUE#'

  subscription: 
    version-number: 5501679

- # ====== Component Setting: NATIVE_YES_NO ====================
  id: 14117332589377560
  identification: 
    name: NATIVE_YES_NO
    type: Item

  settings: 
    attribute-1: Y
    attribute-3: N
    attribute-5: SWITCH_CB

  subscription: 
    version-number: 5501679

application-settings: 
- # ====== Application Setting: ACCESS_CONTROL_SCOPE ===========
  id: 15114989024581608
  identification: 
    name: ACCESS_CONTROL_SCOPE

  value: 
    value: ACL_ONLY
    required: false

  advanced: 
    valid-values: ACL_ONLY, ALL_USERS
    on-upgrade-keep-value: true

  subscription: 
    version-number: 5501679

  configuration: 
    build-option: 'Feature: Access Control' # 15114713307581598

  comments: 
    comments: The default access level given to authenticated users who are not in the access control list

